### ISSUE TITLE
Open Babel test not working with Python 3.7

### ISSUE THREAD

**Issue by berquist** [cclib/cclib#672]
Using Open Babel 2.4.1:
```
$ bash travis/run_travis_tests.sh
.FUnable to load the XYZ reader from OpenBabel.
E
======================================================================
ERROR: test_readfile (test.bridge.testopenbabel.OpenbabelTest)
Try to load an XYZ file with uracyl through Openbabel
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eric/development/cclib_berquist/test/bridge/testopenbabel.py", line 34, in test_readfile
    assert data.natom == 12
AttributeError: 'dict' object has no attribute 'natom'

======================================================================
FAIL: test_makeopenbabel (test.bridge.testopenbabel.OpenbabelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eric/development/cclib_berquist/test/bridge/testopenbabel.py", line 29, in test_makeopenbabel
    assert obconversion.WriteString(obmol).strip() == "InChI=1S/H2O/h1H2"
AssertionError

----------------------------------------------------------------------
Ran 3 tests in 0.002s

FAILED (failures=1, errors=1)
```

**Comment by berquist** [comment]
I'm not sure what happened, but this seems to have been fixed for me.
